app:
  topic:
    income-order-topic: order
    outcome-result-topic: order-response
spring:
  kafka:
    bootstrap-servers: "localhost:29092"
server:
  port: 8084

logging:
  level:
    org.apache.kafka: off